-- MySQL Script generated by MySQL Workbench
-- 09/14/15 16:40:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taxiService
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `taxiService` ;

-- -----------------------------------------------------
-- Schema taxiService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxiService` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `taxiService`;


-- -----------------------------------------------------
-- Table `taxiService`.`bonuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxiService`.`bonuses` ;

CREATE TABLE IF NOT EXISTS `taxiService`.`bonuses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `countBonuses` INT(11) DEFAULT null,
  `discount` INT (45) DEFAULT NULL,
  `customer_id` INT(11) NOT NULL UNIQUE,
  PRIMARY KEY (`id`),
  INDEX `fk_taxiService_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_taxiService_customer`
  FOREIGN KEY (`customer_id`)
  REFERENCES `taxiService`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxiService`.`customer`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `taxiService`.`customer`;

CREATE TABLE `taxiService`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `fullName` VARCHAR (45) DEFAULT NULL,
  `phoneNumber` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxiService`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxiService`.`order` ;

CREATE TABLE IF NOT EXISTS `taxiService`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `departureAddress` VARCHAR(45) DEFAULT NULL,
  `arrivalAddress` VARCHAR(45) DEFAULT NULL,
  `currentDate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_taxiService_customer_id1x` (`customer_id` ASC),
  CONSTRAINT `fk_taxiService_customer1`
  FOREIGN KEY (`customer_id`)
  REFERENCES `taxiService`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxiService`.`calculationOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxiService`.`calculationOrder`;

CREATE TABLE IF NOT EXISTS `taxiService`.`calculationOrder` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `distance` INT(11) DEFAULT NULL,
  `travelTime` TIMESTAMP NULL DEFAULT NULL,
  `timeOfDeparture` TIMESTAMP NULL DEFAULT NULL,
  `arrivalTime` TIMESTAMP NULL DEFAULT NULL,
  `rate` DOUBLE DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `driver_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL UNIQUE,
  PRIMARY KEY (`id`),
  INDEX `fk_taxiService_driver_idx` (`driver_id` ASC),
  CONSTRAINT `fk_taxiService_driver`
  FOREIGN KEY (`driver_id`)
  REFERENCES `taxiService`.`driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_taxiService_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_taxiService_order`
  FOREIGN KEY (`order_id`)
  REFERENCES `taxiService`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxiService`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxiService`.`driver` ;

CREATE TABLE IF NOT EXISTS `taxiService`.`driver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee` VARCHAR(45) DEFAULT NULL,
  `carModel` VARCHAR(45) DEFAULT NULL,
  `carNumber` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;
